import {
    AccountTree,
    PersonOutline,
    NoteAlt,
    Schema,
    FolderShared,
    DownhillSkiing,
    CurrencyExchange,
    Savings,
    MedicalInformation,
    Commute,
    Money,
    AccountBalanceWallet,
    FolderSpecial,
    StarHalf,
    ThumbUp,
    ContactEmergency,
    Portrait,
    PersonPin,
    EventAvailable,
    Topic,
    ChevronRight,
    StarBorder,
    ExpandLess,
    ExpandMore,
    MedicalServices,
    SpaceDashboard,
    Domain,
    Badge,
    Work,
    BeachAccess,
    Payments,
    Handshake,
    Receipt,
    Healing,
    LibraryBooks,
    ReceiptLong,
    FactCheck,
    PersonAdd,
    AssignmentInd,
    RecordVoiceOver,
    Print,
    Gavel,
    ReportProblem,
    Timeline,
    School,
} from "@mui/icons-material";
import { SvgIconProps } from "@mui/material";
import { colorBase } from "../modules/module_general";

interface MenuIcons {
    [key: string]: React.ElementType<SvgIconProps>;
}

export const menusIcon: MenuIcons = {
    AccountTree: AccountTree,
    PersonOutline: PersonOutline,
    NoteAlt: NoteAlt,
    Schema: Schema,
    FolderShared: FolderShared,
    DownhillSkiing: DownhillSkiing,
    CurrencyExchange: CurrencyExchange,
    Savings: Savings,
    MedicalInformation: MedicalInformation,
    Commute: Commute,
    Money: Money,
    AccountBalanceWallet: AccountBalanceWallet,
    FolderSpecial: FolderSpecial,
    StarHalf: StarHalf,
    ThumbUp: ThumbUp,
    ContactEmergency: ContactEmergency,
    Portrait: Portrait,
    PersonPin: PersonPin,
    EventAvailable: EventAvailable,
    Topic: Topic,
    ChevronRight: ChevronRight,
    MedicalServices: MedicalServices,
    SpaceDashboard: SpaceDashboard,
    Domain: Domain,
    Badge: Badge,
    Work: Work,
    BeachAccess: BeachAccess,
    Payments: Payments,
    Handshake: Handshake,
    Receipt: Receipt,
    Healing: Healing,
    LibraryBooks: LibraryBooks,
    ReceiptLong: ReceiptLong,
    FactCheck: FactCheck,
    PersonAdd: PersonAdd,
    AssignmentInd: AssignmentInd,
    RecordVoiceOver: RecordVoiceOver,
    Print: Print,
    Gavel: Gavel,
    ReportProblem: ReportProblem,
    Timeline: Timeline,
    School: School,
};

export const GetMenuIcon = ({
    name_ecran,
    sx = { color: colorBase.colorBase01 },
}: {
    name_ecran: string;
    sx?: any;
}): JSX.Element => {
    const IconComponent = menusIcon[name_ecran] || ChevronRight;
    return <IconComponent sx={{ ...sx }} />;
};
