Imports System.Globalization
Imports System.Threading
Imports DevExpress.Data.PivotGrid
Imports DevExpress.Utils
Imports DevExpress.XtraCharts.Wizard
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraGrid.Views.Grid.ViewInfo
Imports DevExpress.XtraPivotGrid
Imports DevExpress.XtraTab

Public Class Param_Query_Saisi
    Dim imgList As New ImageList
    Dim Tbl As New DataTable
    Friend TableLinks As New DataTable
    Friend SqlText As String
    Dim HeaderVisible, Resum, estPivot As Boolean
    Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        Dim Culture = CultureInfo.CreateSpecificCulture("fr-FR")

        ' The following line provides localization for the application's user interface.
        Thread.CurrentThread.CurrentUICulture = Culture

        ' The following line provides localization for data formats.
        Thread.CurrentThread.CurrentCulture = Culture

        ' Set this culture as the default culture for all threads in this application.  
        ' Note: The following properties are supported in the .NET Framework 4.5+
        CultureInfo.DefaultThreadCurrentCulture = Culture
        CultureInfo.DefaultThreadCurrentUICulture = Culture
    End Sub
    Sub gridView1_CustomDrawRowIndicator(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs) Handles GrdViewSource.CustomDrawRowIndicator
        e.Info.DisplayText = e.RowHandle.ToString()
    End Sub

    Sub Query_Generator(ByVal QueryName As String, ByVal QueryText As String)
        Cod_Query_txt.Text = QueryName
        Nom_Query_txt.Text = QueryText

        With imgList
            .Images.Clear()
            .Images.Add(My.Resources.calendrier)
            .Images.Add(My.Resources.MenuLocal)
            .ImageSize = New Size(10, 10)
        End With


        Dim Cod_Sql As String = "Select * from Param_Query_Criteres where Cod_Query='" & QueryName & "' and Critere<>'@idSoc' order by rang"
        Tbl = DATA_READER_GRD(Cod_Sql)
        Dim C1, C2, C3, C4 As Object
        With Tbl
            For i = 0 To .Rows.Count - 1
                C1 = IsNull(Tbl.Rows(i).Item("Critere"), "")
                C2 = IsNull(Tbl.Rows(i).Item("Lib_Critere"), "")
                C3 = GetDefaultValue(IsNull(.Rows(i).Item("Default_Value"), ""))
                C4 = IsNull(Tbl.Rows(i).Item("Fonction_Critere"), "")
                Criteres_Grd.Rows.Add(C1, C2, C3, C4)
            Next
        End With
    End Sub
    Private Sub Criteres_Grd_CellPainting(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellPaintingEventArgs) Handles Criteres_Grd.CellPainting
        If e.RowIndex < 0 Or e.ColumnIndex <> Valeur.Index Then Exit Sub
        Dim oX = CInt(e.CellBounds.Right - 20)
        Dim oY = CInt(e.CellBounds.Top + e.CellBounds.Height / 2 - My.Resources.MenuLocal.Height / 2)
        e.Paint(e.ClipBounds, DataGridViewPaintParts.Background)

        If Tbl.Rows(e.RowIndex).Item("Fonction_Critere") = "Calender" Then
            e.Graphics.DrawImage(My.Resources.calendar, oX, oY)
            Criteres_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
        ElseIf Tbl.Rows(e.RowIndex).Item("Fonction_Critere") = "Appel_Zoom" Then
            e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
            Criteres_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
        ElseIf Tbl.Rows(e.RowIndex).Item("Fonction_Critere") = "Combo" Then
            e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
            Criteres_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
        ElseIf Tbl.Rows(e.RowIndex).Item("Fonction_Critere") = "Boolean" Then
            e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
            Criteres_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
        Else
            Criteres_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = False
        End If
        ' Paint the rest of the cell
        e.Paint(e.ClipBounds, DataGridViewPaintParts.Border Or DataGridViewPaintParts.ContentForeground)

        ' Tell the DataGridView that you've handled this paint event
        e.Handled = True
    End Sub
    Private Sub Criteres_Grd_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles Criteres_Grd.DoubleClick
        Dim r, c As Integer
        r = Criteres_Grd.CurrentRow.Index
        c = Criteres_Grd.CurrentCell.ColumnIndex
        If c <> Valeur.Index Or r < 0 Then Exit Sub
        Dim Fonction_Critere As String = Criteres_Grd.Item(Type.Index, r).Value
        Dim oCell As DataGridViewTextBoxCell = TryCast(Criteres_Grd.Item(Valeur.Index, r), DataGridViewTextBoxCell)
        Select Case Fonction_Critere
            Case "Calender"
                Appel_Calender(oCell, Me)
            Case "Boolean"
                Appel_Zoom_Boolean(oCell, Me)
            Case "Appel_Zoom"
                Dim Cod_Sql As String = "Select * from Param_Query_Criteres where Critere='" & Criteres_Grd.Item(Critere.Index, r).Value & "' and Cod_Query = '" & Cod_Query_txt.Text & "' order by rang"
                Dim Condition As String = "1=1"
                Dim Tbl As New DataTable
                Tbl = DATA_READER_GRD(Cod_Sql)
                With Tbl
                    If Tbl.Rows.Count > 0 Then
                        If RTrim(LTrim(IsNull(.Rows(0).Item("Condition"), ""))) <> "" Then
                            Condition = IsNull(.Rows(0).Item("Condition"), "")
                            Dim Condition1 As String()
                            Condition1 = Split(Condition, "&")
                            Dim Longeur As Integer = UBound(Condition1)
                            Condition = ""

                            For i As Integer = 0 To Longeur

                                If Condition1(i).Contains("@") Then
                                    For k = 0 To Criteres_Grd.RowCount - 1
                                        If UCase(Criteres_Grd.Item(Critere.Index, k).Value) = UCase(LTrim(RTrim(Condition1(i)))) Then
                                            Condition1(i) = Criteres_Grd.Item(Valeur.Index, k).Value
                                        End If
                                    Next
                                End If

                                Condition = RTrim(Condition.Trim("""")) & RTrim(LTrim(Condition1(i)).Trim(""""))
                            Next
                        End If
                        Appel_Zoom(.Rows(0).Item("Champs_01"), .Rows(0).Item("Champs_02"), .Rows(0).Item("Table_Critere"), Condition, oCell, Me)
                    End If
                End With
            Case "Combo"
                Dim Cod_Sql As String = "Select * from Param_Query_Criteres where Critere='" & Criteres_Grd.Item(Critere.Index, r).Value & "' and Cod_Query = '" & Cod_Query_txt.Text & "' order by rang"
                Dim Condition As String = "1=1"
                Dim Tbl As New DataTable
                Tbl = DATA_READER_GRD(Cod_Sql)
                With Tbl
                    If Tbl.Rows.Count > 0 Then
                        Appel_Zoom_Boolean(oCell, Me, IsNull(.Rows(0).Item("Table_Critere"), ""))
                    End If
                End With
        End Select

    End Sub
    Private Sub Visualiser_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Run_pb.Click
        Request()

    End Sub
    Private Sub TabControl1_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles TabControl1.SelectedIndexChanged
        If TabControl1.SelectedIndex = 0 Then
            TabControl1.TabPages.Remove(TabPage2)
            TabControl1.TabPages.Remove(TabPage3)
        End If
    End Sub
    Private Sub Param_Query_Saisi_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        DevExpress.LookAndFeel.UserLookAndFeel.Default.SetSkinStyle(DevExpress.LookAndFeel.SkinStyle.DevExpress)
        TabControl1.TabPages.Remove(TabPage2)
        TabControl1.TabPages.Remove(TabPage3)
        Dim oMnu As New ToolStripMenuItem
        Dim ocnt As New ContextMenuStrip
        With oMnu
            .Text = "Copier le graphe"
            .Image = My.Resources.Copier
            AddHandler .Click, AddressOf CopierGraphe
        End With
        ocnt.Items.Add(oMnu)
        Chart1.ContextMenuStrip = ocnt
        ToolTip1.SetToolTip(SavePivot_pb, "Enregistrer le schéma actuek du tableau croisé dynamique.")
        ToolTip1.SetToolTip(Excel_pb, "Exporter vers Excel.")
        ToolTip1.SetToolTip(Pdf_pb, "Exporter vers Pdf.")
        ToolTip1.SetToolTip(SumCol_pb, "Afficher les totaux des colonnes.")
        ToolTip1.SetToolTip(SumLig_pb, "Afficher les totaux des Lignes.")
        ToolTip1.SetToolTip(InverserEntete_pb, "Inverser les colonnes et les lignes.")
        ToolTip1.SetToolTip(ChampsCalcule_pb, "Ajouter un champs calculé.")
        ToolTip1.SetToolTip(LoadPivot_pb, "Charger un schéma enregistré.")
    End Sub
    Sub CopierGraphe()
        Dim stream As New System.IO.MemoryStream()
        Chart1.SaveImage(stream, Imaging.ImageFormat.Png)
        Dim bmp As New Bitmap(stream)
        Clipboard.SetDataObject(bmp)
    End Sub
    Sub Request()
        Try

            Dim Cod_Sql As String = "Declare @idSoc int " & vbCrLf & "Set @idSoc=" & Societe.id_Societe
            Dim TblQuery As DataTable = DATA_READER_GRD("select * from Param_Query where Cod_Query='" & Cod_Query_txt.Text & "'")
            TableLinks = DATA_READER_GRD("Select Colonne,Typ_Ecran,LinkTo,Relation from Param_Query_Colonnes where Cod_Query='" & Cod_Query_txt.Text & "'")
            If TblQuery.Rows.Count = 0 Then Return
            If Cod_Query_txt.Text = "" Then Exit Sub
            With Criteres_Grd
                For i = 0 To .RowCount - 1

                    Cod_Sql = Cod_Sql & vbCrLf & " Declare " & IsNull(.Item(Critere.Index, i).Value, "") & " as " & FindLibelle("Typ_Critere", "Cod_Query+Critere", Cod_Query_txt.Text & IsNull(.Item(Critere.Index, i).Value, ""), "Param_Query_Criteres")
                    Cod_Sql = Cod_Sql & vbCrLf & " set " & IsNull(.Item(Critere.Index, i).Value, "") & " = '" & IsNull(.Item(Valeur.Index, i).Value, "") & "'"
                Next
            End With
            Cod_Sql = Cod_Sql & vbCrLf & IsNull(TblQuery.Rows(0)("Cod_Sql"), "")
            SqlText = Cod_Sql
            Dim DTR As DataTable = DATA_READER_GRD(Cod_Sql)
            Dim NatureQuery As String = IsNull(TblQuery.Rows(0)("Nature_Query"), "QRY")
            If NatureQuery = "CHR" Then
                With TabControl1
                    If Not .TabPages.Contains(TabPage3) Then
                        .TabPages.Add(TabPage3)
                        .SelectedTab = TabPage3
                    End If
                End With
                ChargerChart(Chart1, DTR, IsNull(TblQuery.Rows(0)("Typ_Graphe"), "QRY"), IsNull(TblQuery.Rows(0)("Afficher_Graphe_Valeur"), True))
            ElseIf NatureQuery = "EXP" Then
                Dim dialog2 As New SaveFileDialog
                dialog2.FileName = Cod_Query_txt.Text & "_" & Now.Year & Droite("00" & Now.Month, 2) & Droite("00" & Now.Day, 2) & Droite("00" & Now.Hour, 2) & Droite("00" & Now.Minute, 2) & ".txt"
                dialog2.Filter = "Fichiers txt|*.txt"
                dialog2.DefaultExt = "txt"
                dialog2.AddExtension = True
                dialog2.ShowDialog()
                Dim fileName As String = dialog2.FileName
                Dim strLigne As String = ""
                dialog2 = Nothing
                If (fileName <> "") Then
                    Dim sw As New IO.StreamWriter(fileName, True)
                    Cursor = Cursors.WaitCursor
                    Dim Largeur_Fixe As String = IsNull(TblQuery.Rows(0)("Largeur_Fixe"), "")
                    If Largeur_Fixe.Split("|").Length >= 2 Then
                        Dim oArray As New Dictionary(Of String, Integer)
                        For i = 0 To Largeur_Fixe.Split("|").Length - 1
                            oArray.Add(Largeur_Fixe.Split("|")(i).Split(":")(0), ConvertEntier(Largeur_Fixe.Split("|")(i).Split(":")(1)))
                        Next
                        For i = 0 To DTR.Rows.Count - 1
                            strLigne = ""
                            For j = 0 To DTR.Columns.Count - 1
                                strLigne &= setFormatExport(DTR.Rows(i)(j), oArray(DTR.Columns(j).ColumnName), IIf(Gauche(DTR.Columns(j).DataType.Name, 10) = "System.Int" Or DTR.Columns(j).DataType.Name = "System.Decimal" Or DTR.Columns(j).DataType.Name = "System.Double", True, False))
                            Next
                            sw.WriteLine(strLigne)
                        Next
                    Else
                        Dim Separateur As String = IsNull(TblQuery.Rows(0)("Separateur"), ";")
                        For i = 0 To DTR.Rows.Count - 1
                            strLigne = ""
                            For j = 0 To DTR.Columns.Count - 1
                                strLigne &= IIf(strLigne = "", "", Separateur) & DTR.Rows(i)(j)
                            Next
                            sw.WriteLine(strLigne)
                        Next
                    End If
                    sw.Close()
                    Cursor = Cursors.Default
                    If IO.File.Exists(fileName) Then
                        If ShowMessageBox("Ficher terminé, voulez-vous l'ouvrir?", "Ouvrir", MessageBoxButtons.OKCancel, msgIcon.Question) = DialogResult.OK Then StartPrograme(fileName)
                    End If
                End If
            Else
                With MyGrdSource
                    .DataSource = DTR
                End With
                With TabControl1
                    If Not .TabPages.Contains(TabPage2) Then
                        .TabPages.Add(TabPage2)
                        .SelectedTab = TabPage2
                    End If
                End With
                With GrdViewSource
                    .OptionsView.EnableAppearanceEvenRow = True
                    .OptionsView.ColumnAutoWidth = False
                    .OptionsBehavior.Editable = False
                    .OptionsNavigation.AutoFocusNewRow = True
                    .BestFitColumns()
                    .IndicatorWidth = 45
                    .ExpandAllGroups()
                End With
                For Each cl As DataColumn In DTR.Columns
                    Dim grdCol As DevExpress.XtraGrid.Columns.GridColumn = GrdViewSource.Columns(cl.ColumnName)
                    If Not grdCol Is Nothing Then
                        If TableLinks.Select("Colonne='" & cl.ColumnName.Replace("'", "''") & "'").Length > 0 Then
                            With grdCol
                                .AppearanceCell.ForeColor = Color.Blue

                            End With
                        End If
                        With grdCol
                            If .ColumnType Is GetType(Double) Or .ColumnType Is GetType(Decimal) Then
                                .DisplayFormat.FormatType = FormatType.Numeric
                                .DisplayFormat.FormatString = "N2"
                            End If
                        End With
                    End If
                Next

                GrdViewSource.OptionsView.ShowColumnHeaders = CBool(HeaderVisible)

                If CBool(Resum) = True And DTR.Rows.Count > 0 Then
                    Dim str As String = IsNull(TblQuery.Rows(0)("ColonneSomme"), "")
                    If str <> "" Then
                        Dim ostr() As String = str.Split({";"}, StringSplitOptions.RemoveEmptyEntries)
                        For i = 0 To ostr.Length - 1
                            Dim cl As DevExpress.XtraGrid.Columns.GridColumn = GrdViewSource.Columns(ostr(i))
                            If Not cl Is Nothing Then
                                cl.SummaryItem.SummaryType = DevExpress.Data.SummaryItemType.Sum
                            End If
                        Next
                    End If
                End If
                If Not estPivot Then
                    If XtraTabControl1.TabPages.Contains(tb_Pivot) Then XtraTabControl1.TabPages.Remove(tb_Pivot)
                    If XtraTabControl1.TabPages.Contains(tb_Detail) Then XtraTabControl1.TabPages.Remove(tb_Detail)
                Else
                    If CBool(HeaderVisible) Then MyPivotMaj(DTR)
                    If Not XtraTabControl1.TabPages.Contains(tb_Pivot) Then XtraTabControl1.TabPages.Add(tb_Pivot)
                    If Not XtraTabControl1.TabPages.Contains(tb_Detail) Then XtraTabControl1.TabPages.Add(tb_Detail)
                End If
            End If

        Catch ex As Exception
            SqlErreur = SqlText
            ErrorMsg(ex)
        End Try
    End Sub
#Region "Pivot"
    Sub MyPivotMaj(Tbls As DataTable)
        With MyPivot
            .DataSource = Tbls
            .OptionsCustomization.CustomizationFormStyle = Customization.CustomizationFormStyle.Excel2007
            .FieldsCustomization(_Pnl)
            .BeginUpdate()
            For Each c As DataColumn In Tbls.Columns
                Dim Cl As New PivotGridField
                With Cl
                    .Caption = c.Caption
                    .FieldName = c.ColumnName
                    .Options.ShowGrandTotal = True
                    .Options.ShowTotals = True
                    .Options.ShowInCustomizationForm = True
                    .Options.ShowInExpressionEditor = True

                    Select Case c.DataType
                        Case GetType(Double), GetType(Decimal)
                            .CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                            .CellFormat.FormatString = "N2"
                            .SummaryType = PivotSummaryType.Sum
                        Case GetType(Int32), GetType(Int16), GetType(Int64), GetType(Integer), GetType(Long)
                            .CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                            .CellFormat.FormatString = "N0"
                            .SummaryType = PivotSummaryType.Sum
                        Case Else
                            .SummaryType = PivotSummaryType.Count
                    End Select
                End With
                .Fields.Add(Cl)
            Next
            .EndUpdate()
            .RetrieveFields(PivotArea.FilterArea, False)
        End With
    End Sub
    Private Sub pivotGridControl1_MouseUp(ByVal sender As Object, ByVal e As MouseEventArgs) Handles MyPivot.MouseUp
        MyPivot.ContextMenuStrip = Nothing
        If e.Button = MouseButtons.Right Then

            Dim pt As Point = MyPivot.PointToClient(MousePosition)
            Dim hit As PivotGridHitInfo = MyPivot.CalcHitInfo(pt)
            If hit.HitTest = PivotGridHitTest.Cell Then
                If Not hit.CellInfo Is Nothing Then
                    If Not hit.CellInfo.DataField Is Nothing Then
                        If hit.CellInfo.DataField.Area = PivotArea.DataArea Then
                            MyPivot.ContextMenuStrip = ContextMenuStrip1
                            ContextMenuStrip1.Tag = hit.CellInfo.DataField
                        End If
                    End If
                End If
            ElseIf hit.HitTest = PivotGridHitTest.Value Then
                MyPivot.ContextMenuStrip = ContextMenuStrip3
                ContextMenuStrip3.Tag = hit.ValueInfo.Field
            Else
                MyPivot.ContextMenuStrip = Nothing
            End If
        End If
    End Sub
    Private Sub SommeToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles SommeToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        ofield.SummaryType = PivotSummaryType.Sum
    End Sub
    Private Sub NombreToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles NombreToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        ofield.SummaryType = PivotSummaryType.Count
    End Sub
    Private Sub MinToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles MinToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        ofield.SummaryType = PivotSummaryType.Min
    End Sub
    Private Sub MaxToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles MaxToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        ofield.SummaryType = PivotSummaryType.Max
    End Sub
    Private Sub MoyenneToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles MoyenneToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        ofield.SummaryType = PivotSummaryType.Average
    End Sub
    Private Sub MyPivot_CellDoubleClick(sender As Object, e As PivotCellEventArgs) Handles MyPivot.CellDoubleClick
        MyGrdDetail.Tag = e.CreateDrillDownDataSource
        RaffraichirMyGrid()
        XtraTabControl1.SelectedTabPageIndex = 2
    End Sub
    Sub RaffraichirMyGrid()
        If Not MyGrdDetail.Tag.GetType Is GetType(PivotListDrillDownDataSource) Then Return
        MyGrdDetail.DataSource = MyGrdDetail.Tag
        With GrdViewDetail
            For Each cl As DevExpress.XtraGrid.Columns.GridColumn In .Columns
                If cl.ColumnType Is GetType(Double) Or cl.ColumnType Is GetType(Decimal) Then
                    cl.DisplayFormat.FormatType = FormatType.Numeric
                    cl.DisplayFormat.FormatString = "N2"
                End If
            Next
            .OptionsView.EnableAppearanceEvenRow = True
            .OptionsView.ColumnAutoWidth = False
            .OptionsBehavior.Editable = False
            .OptionsNavigation.AutoFocusNewRow = True
            .BestFitColumns()
            .ExpandAllGroups()
        End With
    End Sub
    Private Sub MyPivot_FieldAreaChanged(sender As Object, e As PivotFieldEventArgs) Handles MyPivot.FieldAreaChanged
        With e.Field
            If .Area = PivotArea.DataArea Then
                .Options.ShowSummaryTypeName = True
            Else
                .Options.ShowSummaryTypeName = False
            End If
            .BestFit()
            Select Case e.Field.DataType
                Case GetType(Double), GetType(Decimal)
                    .CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                    .CellFormat.FormatString = "N2"
                    .SummaryType = PivotSummaryType.Sum
                Case GetType(Int32), GetType(Int16), GetType(Int64), GetType(Integer), GetType(Long)
                    .CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                    .CellFormat.FormatString = "N0"
                    .SummaryType = PivotSummaryType.Sum
                Case Else
                    .SummaryType = PivotSummaryType.Count
            End Select
        End With
    End Sub
    Private Sub FormatDeNombreToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles FormatDeNombreToolStripMenuItem.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        Dim ofrm As String = IsNull(ofield.CellFormat.FormatString, "")
        Dim f As New Zoom_NombreFormat
        With f
            .Sep_chk.Checked = (Gauche(ofrm, 1) = "N" Or Gauche(ofrm, 1) = "C")
            If ofrm.Length > 0 Then
                If IsNumeric(Droite(ofrm, ofrm.Length - 1)) Then
                    .nbDec.Value = CInt(Droite(ofrm, ofrm.Length - 1))
                ElseIf ofrm.Contains("#") Then
                    .nbDec.Value = CInt(Droite(ofrm, ofrm.Length - 1).Replace(".", "").Length)
                End If
            End If
            .ShowDialog()
            If .itsOk Then
                If .Sep_chk.Checked Then
                    ofield.CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                    ofield.CellFormat.FormatString = "N" & .nbDec.Value
                Else
                    ofield.CellFormat.FormatType = DevExpress.Utils.FormatType.Numeric
                    ofield.CellFormat.FormatString = IIf(.nbDec.Value > 0, "#." & StrDup(CInt(.nbDec.Value), "#"), "#")
                End If
            End If
        End With
    End Sub
    Private Sub AfficherTousLesGroupesToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles AfficherTousLesGroupesToolStripMenuItem.Click
        With GrdViewDetail
            If AfficherTousLesGroupesToolStripMenuItem.Checked Then
                .CollapseAllGroups()
                AfficherTousLesGroupesToolStripMenuItem.Checked = False
            Else
                .ExpandAllGroups()
                AfficherTousLesGroupesToolStripMenuItem.Checked = True
            End If
        End With
    End Sub
    Private Sub RaffraichirToolStripMenuItem_Click(sender As Object, e As EventArgs) Handles RaffraichirToolStripMenuItem.Click
        If Not MyGrdDetail.Tag.GetType Is GetType(PivotListDrillDownDataSource) Then Return
        MyGrdDetail.DataSource = MyGrdDetail.Tag

        With GrdViewDetail
            .RefreshData()
            For Each cl As DevExpress.XtraGrid.Columns.GridColumn In .Columns
                cl.Visible = True
            Next
        End With
    End Sub
    Private Sub AfficherLesTopToolStripMenuItem1_Click(sender As Object, e As EventArgs) Handles AfficherLesTopToolStripMenuItem1.Click
        Dim ofield As New PivotGridField
        If MyPivot.ContextMenuStrip.Tag.GetType = GetType(PivotGridField) Then ofield = MyPivot.ContextMenuStrip.Tag
        If ofield Is Nothing Then Return
        Dim lst As List(Of PivotGridField) = MyPivot.GetFieldsByArea(PivotArea.DataArea)
        Dim f As New Zoom_PivotGridTopValue
        With f
            For i = 0 To lst.Count - 1
                f.TrierPar_cbo.Items.Add(lst(i))
            Next
            .TopValue.Value = ofield.TopValueCount
            If .TopValue.Value > 0 Then .Tout_chk.Checked = False
            If Not ofield.SortBySummaryInfo Is Nothing Then
                .Tri_chk.Checked = True
                .SensTri_cbo.SelectedIndex = ofield.SortOrder
                .TrierPar_cbo.SelectedIndex = lst.IndexOf(ofield.SortBySummaryInfo.Field)
            End If
            .ShowDialog()
            If .itsOk Then
                If Not .Tout_chk.Checked Then
                    If .Tri_chk.Checked Then
                        ofield.SortBySummaryInfo.Field = lst(.TrierPar_cbo.SelectedIndex)
                        ofield.SortOrder = .SensTri_cbo.SelectedIndex
                    End If
                    ofield.TopValueShowOthers = .AfficherAutres_chk.Checked
                    ofield.TopValueCount = .TopValue.Value
                Else
                    ofield.TopValueCount = 0
                End If
            End If
        End With
    End Sub
    Private Sub ButtonItem1_Click(sender As Object, e As EventArgs) Handles Excel_pb.Click
        Dim SaveFileDialog1 As New SaveFileDialog
        SaveFileDialog1.InitialDirectory = importPath
        SaveFileDialog1.Filter = "Excel (*.xlsx*)|*.xlsx"
        If SaveFileDialog1.ShowDialog = DialogResult.OK Then
            Select Case True
                Case XtraTabControl1.SelectedTabPage Is tb_Source
                    MyGrdSource.ExportToXlsx(SaveFileDialog1.FileName)
                Case XtraTabControl1.SelectedTabPage Is tb_Detail
                    MyGrdDetail.ExportToXlsx(SaveFileDialog1.FileName)
                Case XtraTabControl1.SelectedTabPage Is tb_Pivot
                    MyPivot.ExportToXlsx(SaveFileDialog1.FileName, True)
                Case XtraTabControl1.SelectedTabPage Is tb_Graph
                    ChartControl1.ExportToXlsx(SaveFileDialog1.FileName)
            End Select
            importPath = System.IO.Path.GetDirectoryName(SaveFileDialog1.FileName)
            If ShowMessageBox("Voulez-vous ouvrir le fichier d'export?", "Export", MessageBoxButtons.OKCancel, msgIcon.Question) = DialogResult.OK Then
                StartPrograme(SaveFileDialog1.FileName)
            End If
        End If
    End Sub
    Private Sub ButtonItem8_Click(sender As Object, e As EventArgs) Handles Pdf_pb.Click
        Dim SaveFileDialog1 As New SaveFileDialog
        SaveFileDialog1.InitialDirectory = importPath

        SaveFileDialog1.Filter = "Pdf (*.pdf*)|*.pdf"
        If SaveFileDialog1.ShowDialog = DialogResult.OK Then
            Select Case True
                Case XtraTabControl1.SelectedTabPage Is tb_Source
                    MyGrdSource.ExportToPdf(SaveFileDialog1.FileName)
                Case XtraTabControl1.SelectedTabPage Is tb_Detail
                    MyGrdDetail.ExportToPdf(SaveFileDialog1.FileName)
                Case XtraTabControl1.SelectedTabPage Is tb_Pivot
                    MyPivot.ExportToPdf(SaveFileDialog1.FileName)
                Case XtraTabControl1.SelectedTabPage Is tb_Graph
                    ChartControl1.ExportToPdf(SaveFileDialog1.FileName)
            End Select
            importPath = System.IO.Path.GetDirectoryName(SaveFileDialog1.FileName)
            If ShowMessageBox("Voulez-vous ouvrir le fichier d'export?", "Export", MessageBoxButtons.OKCancel, msgIcon.Question) = DialogResult.OK Then
                StartPrograme(SaveFileDialog1.FileName)
            End If
        End If
    End Sub
    Private Sub TotLig_D_Click(sender As Object, e As EventArgs) Handles SumLig_pb.Click
        MyPivot.OptionsView.ShowRowGrandTotals = Not sumLig
        sumLig = Not sumLig
        ToolTip1.SetToolTip(SumLig_pb, If(sumLig, "Masquer les totaux des Lignes.", "Afficher les totaux des Lignes."))
    End Sub
    Dim sumCol As Boolean = True
    Dim sumLig As Boolean = True
    Dim InverserEntete As Boolean = True
    Private Sub SumCol_pb_Click(sender As Object, e As EventArgs) Handles SumCol_pb.Click
        MyPivot.OptionsView.ShowColumnGrandTotals = Not sumCol
        sumCol = Not sumCol
        ToolTip1.SetToolTip(SumCol_pb, If(sumCol, "Masquer les totaux des Colonnes.", "Afficher les totaux des Colonnes."))
    End Sub
    Private Sub ButtonItem2_Click(sender As Object, e As EventArgs) Handles ChampsCalcule_pb.Click
        Dim f As New Zoom_PivotAjouterChamps
        With f
            .PivotGrid = MyPivot
            .ShowDialog()
        End With
    End Sub
    Private Sub InverserEntete_pb_Click(sender As Object, e As EventArgs) Handles InverserEntete_pb.Click
        If Not MyPivot.OptionsDataField.Area = PivotDataArea.RowArea Then
            MyPivot.OptionsDataField.Area = PivotDataArea.RowArea
            InverserEntete = True
        Else
            MyPivot.OptionsDataField.Area = PivotDataArea.ColumnArea
            InverserEntete = False
        End If
    End Sub
#End Region
    Private Sub Cod_Query_Txt_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Cod_Query_txt.TextChanged
        Try
            HeaderVisible = FindLibelle("HeaderVisible", "Cod_Query", Cod_Query_txt.Text, "Param_Query")
            estPivot = FindLibelle("estPivot", "Cod_Query", Cod_Query_txt.Text, "Param_Query")
            Resum = FindLibelle("Resume", "Cod_Query", Cod_Query_txt.Text, "Param_Query")
        Catch ex As Exception
            ErrorMsg(ex)
        End Try

    End Sub
    Function setFormatExport(Str As Object, NbChar As Integer, Optional EstNumeric As Boolean = False) As String
        If Not EstNumeric Then
            Return Gauche(IsNull(Str, "").Replace(Chr(13), Chr(32)) & StrDup(NbChar, Chr(32)), NbChar)
        Else
            Return Droite(StrDup(NbChar, "0") & IsNull(Str, 0), NbChar)
        End If

    End Function
    Private Sub XtraTabControl1_SelectedPageChanged(sender As Object, e As TabPageChangedEventArgs) Handles XtraTabControl1.SelectedPageChanged
        SumCol_pb.Visible = (XtraTabControl1.SelectedTabPage Is tb_Pivot)
        SumLig_pb.Visible = SumCol_pb.Visible
        ChampsCalcule_pb.Visible = SumLig_pb.Visible
        InverserEntete_pb.Visible = SumLig_pb.Visible
        SavePivot_pb.Visible = SumLig_pb.Visible
        LoadPivot_pb.Visible = SumLig_pb.Visible

        ChampsCalcule_pb.Refresh()
        InverserEntete_pb.Refresh()
        SavePivot_pb.Refresh()
        LoadPivot_pb.Refresh()
    End Sub
    Private Sub GridView1_MouseMove(sender As System.Object, e As EventArgs) Handles GrdViewSource.MouseMove
        Dim hitInfo As GridHitInfo = GrdViewSource.CalcHitInfo(MyGrdSource.PointToClient(MousePosition))
        If Not hitInfo.Column Is Nothing Then
            If TableLinks.Select("Colonne='" & hitInfo.Column.FieldName.Replace("'", "''") & "'").Length > 0 Then
                MyGrdSource.Cursor = Cursors.Hand
            Else
                MyGrdSource.Cursor = Cursors.Default
            End If
        Else
            MyGrdSource.Cursor = Cursors.Default
        End If
    End Sub

    Private Sub SavePivot_pb_Click(sender As Object, e As EventArgs) Handles SavePivot_pb.Click
        Try
            Dim SaveFileDialog1 As New SaveFileDialog
            SaveFileDialog1.InitialDirectory = importPath
            If SaveFileDialog1.ShowDialog = DialogResult.OK Then
                MyPivot.SaveLayoutToXml(SaveFileDialog1.FileName)
                importPath = System.IO.Path.GetDirectoryName(SaveFileDialog1.FileName)
                ShowMessageBox("Enregistré")
            End If
        Catch ex As Exception
            ShowMessageBox(ex.Message)
        End Try
    End Sub

    Private Sub LoadPivot_pb_Click(sender As Object, e As EventArgs) Handles LoadPivot_pb.Click
        Try
            Dim opdl As New OpenFileDialog
            opdl.InitialDirectory = importPath
            If opdl.ShowDialog = DialogResult.OK Then
                Dim filePath As String = opdl.FileName
                MyPivot.RestoreLayoutFromXml(opdl.FileName)
                importPath = System.IO.Path.GetDirectoryName(opdl.FileName)
            End If
        Catch ex As Exception
            ShowMessageBox(ex.Message)
        End Try

    End Sub
    Private Sub GrdViewSource_DoubleClick(sender As Object, e As EventArgs) Handles GrdViewSource.DoubleClick
        Try
            Dim hitInfo As GridHitInfo = GrdViewSource.CalcHitInfo(MyGrdSource.PointToClient(MousePosition))
            If Not hitInfo.Column Is Nothing Then
                If TableLinks.Select("Colonne='" & hitInfo.Column.FieldName.Replace("'", "''") & "'").Length > 0 Then
                    Dim r As Integer = hitInfo.RowHandle
                    Dim oTypEcr, oLinkTo, oRelation, Relation() As String
                    Dim oCritere, ValeurCritere, Variable, ValeurVariable As New ArrayList
                    oTypEcr = TableLinks.Rows(0)("Typ_Ecran")
                    oLinkTo = TableLinks.Rows(0)("LinkTo")
                    oRelation = TableLinks.Rows(0)("Relation")
                    Relation = Split(oRelation, ";")
                    ' Chargement des variables de critères et leurs valeurs
                    For i = 0 To Relation.Length - 1
                        oCritere.Add(Split(Relation(i), ":=")(0))
                        If Microsoft.VisualBasic.Left(Split(Relation(i), ":=")(1).ToUpper.Trim, 1) = "#" Then
                            Dim cl As Integer = CInt(Split(Relation(i), ":=")(1).ToUpper.Replace("#", ""))
                            ValeurCritere.Add(GrdViewSource.GetRowCellValue(r, GrdViewSource.Columns(cl)))
                        ElseIf Microsoft.VisualBasic.Left(Split(Relation(i), ":=")(1).ToUpper.Trim, 1) = "@" Then
                            For j = 0 To Criteres_Grd.RowCount - 1
                                If Not Criteres_Grd.Item(Critere.Index, j).Value Is Nothing Then
                                    If Split(Relation(i), ":=")(1).ToUpper = Criteres_Grd.Item(Critere.Index, j).Value.ToUpper Then
                                        ValeurCritere.Add(Criteres_Grd.Item(Valeur.Index, j).Value)
                                    End If
                                End If
                            Next

                        ElseIf Microsoft.VisualBasic.Left(Split(Relation(i), ":=")(1).ToUpper.Trim, 1) = Chr(34) Then
                            ValeurCritere.Add(Split(Relation(i), ":=")(1).Replace(Chr(34), ""))

                        ElseIf Microsoft.VisualBasic.Left(Split(Relation(i), ":=")(1).ToUpper.Trim, 1) = "{" Then
                            ValeurCritere.Add(Split(Relation(i), ":=")(1).Replace("{", "").Replace("}", ""))
                            If ValeurCritere(oCritere.Count - 1).Contains("#") Then
                                Dim Tbl As String() = ValeurCritere(oCritere.Count - 1).Split("#")
                                For j = 1 To Tbl.Length - 1 Step 2
                                    Variable.Add("#" & Tbl(j).Split(" ")(0).Replace("'", ""))
                                    ValeurVariable.Add(GrdViewSource.GetRowCellValue(r, CInt(Tbl(j).Split(" ")(0).Replace("'", ""))))
                                Next
                            End If
                            If ValeurCritere(oCritere.Count - 1).Contains("@") Then
                                For j = 0 To Criteres_Grd.RowCount - 1
                                    If Not Criteres_Grd.Item(Critere.Index, j).Value Is Nothing Then
                                        If ValeurCritere(oCritere.Count - 1).ToUpper.Contains(Criteres_Grd.Item(Critere.Index, j).Value.ToUpper) Then
                                            Variable.Add(Criteres_Grd.Item(Critere.Index, j).Value)
                                            ValeurVariable.Add(Criteres_Grd.Item(Valeur.Index, j).Value)
                                        End If
                                    End If
                                Next
                            End If
                            For j = 0 To Variable.Count - 1
                                ValeurCritere(oCritere.Count - 1) = ValeurCritere(oCritere.Count - 1).Replace(Variable(j), "'" & ValeurVariable(j) & "'")
                            Next
                            ValeurCritere(oCritere.Count - 1) = CnExecuting(ValeurCritere(oCritere.Count - 1)).Fields(0).Value

                        End If
                    Next

                    Select Case oTypEcr
                        Case "ECR"
                            Dim f As New Form
                            f = CType(System.Activator.CreateInstance(System.Type.GetType("RHP." & oLinkTo)), Form)
                            f.Text = FindLibelle("Text_Ecran", "Name_Ecran", oLinkTo, "Controle_Menu") & " " & GrdViewSource.GetRowCellValue(r, hitInfo.Column)
                            For i = 0 To oCritere.Count - 1
                                Affectation(f, oCritere(i), ValeurCritere(i))
                            Next
                            newShowEcran(f)
                        Case "QRY"

                            Dim f As New Param_Query_Saisi
                            f.Cod_Query_txt.Text = oLinkTo
                            f.Nom_Query_txt.Text = FindLibelle("Text_Ecran", "Name_Ecran", oLinkTo, "Controle_Menu")
                            f.Text = f.Nom_Query_txt.Text
                            f.Query_Generator(oLinkTo, f.Text)
                            newShowEcran(f)
                            For i = 0 To oCritere.Count - 1
                                Affectation(f, oCritere(i), ValeurCritere(i))
                            Next
                            f.Request()
                    End Select

                End If
            End If
        Catch ex As Exception
            ShowMessageBox(ex.Message)
        End Try
    End Sub
    Private Sub Close_pb_Click(sender As Object, e As EventArgs)
        Me.Close()
    End Sub
    Private Sub Criteres_Grd_CellMouseMove(sender As Object, e As DataGridViewCellMouseEventArgs) Handles Criteres_Grd.CellMouseMove
        If e.ColumnIndex < 0 Or e.RowIndex < 0 Then Return
        If Criteres_Grd.Rows.Count = 0 Then Return
        If e.ColumnIndex = Valeur.Index And Criteres_Grd.Item(e.ColumnIndex, e.RowIndex).ReadOnly Then
            Criteres_Grd.Cursor = Cursors.Hand
        Else
            Criteres_Grd.Cursor = Cursors.Default
        End If
    End Sub
    Function GetDefaultValue(ByVal Relation) As String
        Dim Variable As New ArrayList
        Dim ValeurVariable As New ArrayList
        Try
            ' Chargement des variables de critères et leurs valeurs
            If Microsoft.VisualBasic.Left(Relation, 1) = Chr(34) Then
                Relation = Relation.Replace(Chr(34), "")
            End If
            If Microsoft.VisualBasic.Left(Relation, 1) = "{" Then
                Relation = Relation.Replace("{", "").Replace("}", "")
                If Relation.Contains("#") Then
                    Dim Tbl As String() = Relation.Split("#")
                    For j = 1 To Tbl.Length - 1 Step 2
                        Variable.Add("#" & Tbl(j).Split(" ")(0))
                        ValeurVariable.Add(GrdViewSource.GetRowCellValue(GrdViewSource.FocusedRowHandle, CInt(Tbl(j).Split(" ")(0))))
                    Next
                End If
                If Relation.Contains("@") Then

                    For j = 0 To Criteres_Grd.RowCount - 1

                        If Not Criteres_Grd.Item(Critere.Index, j).Value Is Nothing Then
                            If Relation.ToUpper.Contains(Criteres_Grd.Item(Critere.Index, j).Value.ToUpper) Then
                                Variable.Add(Criteres_Grd.Item(Critere.Index, j).Value)
                                ValeurVariable.Add(Criteres_Grd.Item(Valeur.Index, j).Value)
                            End If
                        End If
                    Next
                End If
                For j = 0 To Variable.Count - 1
                    If Relation.toupper.contains(Variable(j).toupper) Then
                        Relation = Relation.Replace(Variable(j), "'" & ValeurVariable(j) & "'")
                    End If
                Next
                Relation = IsNull(CnExecuting(Relation).Fields(0).Value, "")
                'Cas des Variables Globales
            ElseIf Relation.ToString.Trim.ToUpper.Contains("GV_") Then
                Relation = GlobalVar(Relation.trim.ToString)

            End If
        Catch ex As Exception
            ErrorMsg(ex)
        End Try
        Return Relation
    End Function

    Private Sub ChartControl1_DoubleClick(sender As Object, e As EventArgs) Handles ChartControl1.DoubleClick
        Dim wizard As New ChartWizard(ChartControl1)
        ' Obtain a Data page.  
        Dim page As WizardDataPage = wizard.DataPage

        ' Hide the tabs related to a data source on the Data page.  
        page.HiddenPageTabs.Add(DataPageTab.AutoCreatedSeries)
        page.HiddenPageTabs.Add(DataPageTab.SeriesBinding)

        ' Hide all other Page Group and leave the Appearance for colour setting  
        wizard.TitlePage.Group.UnregisterPage(wizard.TitlePage)
        'wizard.ChartTypePage.Group.UnregisterPage(wizard.ChartTypePage)  
        wizard.SeriesPage.Group.UnregisterPage(wizard.SeriesPage)
        wizard.DataPage.Group.UnregisterPage(wizard.DataPage)
        wizard.ChartPage.Group.UnregisterPage(wizard.ChartPage)
        wizard.DiagramPage.Group.UnregisterPage(wizard.DiagramPage)
        wizard.PanePage.Group.UnregisterPage(wizard.PanePage)
        wizard.AxisPage.Group.UnregisterPage(wizard.AxisPage)
        wizard.SeriesLabelsPage.Group.UnregisterPage(wizard.SeriesLabelsPage)
        wizard.SeriesViewPage.Group.UnregisterPage(wizard.SeriesViewPage)
        wizard.LegendPage.Group.UnregisterPage(wizard.LegendPage)
        wizard.AnnotationPage.Group.UnregisterPage(wizard.AnnotationPage)
        wizard.AppearancePage.Group.UnregisterPage(wizard.AppearancePage)

        ' Invoke the Wizard window.  
        wizard.ShowDialog()

        ShowMessageBox("Drill down may not work when chart type has been changed! ", "Report Presentation",
          MessageBoxButtons.OKCancel, msgIcon.Warning)

        'Dim checkType As Boolean = Me.ChartControl2.Diagram.GetType().Equals(ViewType.Pie3D)  
        If ChartControl1.Diagram.GetType() Is GetType(DevExpress.XtraCharts.SimpleDiagram3D) Then
            CType(ChartControl1.Diagram, DevExpress.XtraCharts.SimpleDiagram3D).RuntimeRotation = True
            CType(ChartControl1.Diagram, DevExpress.XtraCharts.SimpleDiagram3D).RuntimeZooming = True
        End If
    End Sub
    Private Sub Close_pb_Click_1(sender As Object, e As EventArgs) Handles Close_pb.Click
        Me.Close()
    End Sub
End Class