import type { WidgetDefinition } from "./types";

export const MOCK_AVAILABLE_WIDGETS: WidgetDefinition[] = [
  // KPIs
  {
    id: "kpi-effectif",
    title: "Effectif total",
    type: "kpi",
    sourceType: "backend",
    icon: "Groups",
    color: "#2e7d32",
    defaultSpan: 3,
    description: "Nombre total de collaborateurs actifs",
    dataConfig: { objectName: "agents", field: "id", aggregation: "count" },
  },
  {
    id: "kpi-absenteisme",
    title: "Taux d'absentéisme",
    type: "kpi",
    sourceType: "backend",
    icon: "TrendingUp",
    color: "#f57c00",
    defaultSpan: 3,
    description: "Taux d'absentéisme du mois en cours",
    dataConfig: { objectName: "absences", field: "id", aggregation: "count" },
  },
  {
    id: "kpi-conges-attente",
    title: "Congés en attente",
    type: "kpi",
    sourceType: "backend",
    icon: "PendingActions",
    color: "#1976d2",
    defaultSpan: 3,
    description: "Nombre de demandes de congé en attente de validation",
    dataConfig: { objectName: "conges", field: "id", aggregation: "count", filters: { statut: "En attente" } },
  },
  {
    id: "kpi-prets-attente",
    title: "Demandes de prêt",
    type: "kpi",
    sourceType: "backend",
    icon: "AccountBalance",
    color: "#8e24aa",
    defaultSpan: 3,
    description: "Nombre de demandes de prêt en attente",
    dataConfig: { objectName: "prets", field: "id", aggregation: "count", filters: { statut: "En attente" } },
  },
  // Charts
  {
    id: "chart-repartition-dept",
    title: "Répartition par département",
    type: "chart",
    chartType: "pie",
    sourceType: "backend",
    icon: "PieChart",
    color: "#1976d2",
    defaultSpan: 6,
    description: "Répartition des effectifs par département",
    dataConfig: { objectName: "agents", field: "id", aggregation: "count", groupBy: "departement" },
  },
  {
    id: "chart-evolution-absences",
    title: "Évolution des absences",
    type: "chart",
    chartType: "line",
    sourceType: "backend",
    icon: "ShowChart",
    color: "#f57c00",
    defaultSpan: 6,
    description: "Évolution du nombre d'absences par mois",
    dataConfig: { objectName: "absences", field: "id", aggregation: "count", groupBy: "mois" },
  },
  {
    id: "chart-top-rubriques",
    title: "Top 5 rubriques de paie",
    type: "chart",
    chartType: "bar",
    sourceType: "backend",
    icon: "BarChart",
    color: "#2e7d32",
    defaultSpan: 6,
    description: "Les 5 rubriques de paie les plus élevées",
    dataConfig: { objectName: "bulletins", field: "montant", aggregation: "sum", groupBy: "rubrique" },
  },
  {
    id: "chart-effectif-mois",
    title: "Effectif par mois",
    type: "chart",
    chartType: "area",
    sourceType: "backend",
    icon: "Timeline",
    color: "#8e24aa",
    defaultSpan: 6,
    description: "Évolution de l'effectif sur les 12 derniers mois",
    dataConfig: { objectName: "agents", field: "id", aggregation: "count", groupBy: "mois" },
  },
  // Tables
  {
    id: "table-conges-recents",
    title: "Dernières demandes de congé",
    type: "table",
    sourceType: "backend",
    icon: "TableChart",
    color: "#1976d2",
    defaultSpan: 12,
    description: "Tableau des 5 dernières demandes de congé",
    dataConfig: { objectName: "conges", field: "id", aggregation: "count" },
  },
  {
    id: "table-agents-recents",
    title: "Nouveaux arrivants",
    type: "table",
    sourceType: "backend",
    icon: "TableChart",
    color: "#2e7d32",
    defaultSpan: 6,
    description: "Tableau des derniers agents recrutés",
    dataConfig: { objectName: "agents", field: "id", aggregation: "count" },
  },
  // Lists
  {
    id: "list-quickactions",
    title: "Accès Rapide",
    type: "list",
    sourceType: "standard",
    standardId: "quickActions",
    icon: "Apps",
    color: "#2e7d32",
    defaultSpan: 6,
    description: "Raccourcis vers les écrans fréquents",
  },
  {
    id: "list-parapheur",
    title: "Parapheur",
    type: "list",
    sourceType: "standard",
    standardId: "parapheur",
    icon: "CreateOutlined",
    color: "#d32f2f",
    defaultSpan: 6,
    description: "Documents en attente de signature",
  },
  {
    id: "list-weather",
    title: "Météo",
    type: "list",
    sourceType: "standard",
    standardId: "weather",
    icon: "CloudOutlined",
    color: "#f57c00",
    defaultSpan: 3,
    description: "Météo du jour",
  },
  {
    id: "list-blogs",
    title: "Actualités RH",
    type: "list",
    sourceType: "standard",
    standardId: "blogs",
    icon: "Newspaper",
    color: "#1976d2",
    defaultSpan: 12,
    description: "Liste des actualités RH",
  },
  {
    id: "list-notifications",
    title: "À faire & Notifications",
    type: "list",
    sourceType: "standard",
    standardId: "notifications",
    icon: "NotificationsOutlined",
    color: "#8e24aa",
    defaultSpan: 6,
    description: "Liste des notifications et tâches",
  },
];
