Imports System.ComponentModel
Imports System.Globalization
Imports System.Net
Imports System.Threading
Imports System.IO
Public Class Param_Python_Saisi
    Dim imgList As New ImageList
    Dim Tbl As New DataTable
    Friend TableLinks As New DataTable
    Dim codeText As String = ""
    Dim oTmr As New System.Windows.Forms.Timer
    Dim startTime As Date = Now
    Dim withConn As Boolean = False
    Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        Dim Culture = CultureInfo.CreateSpecificCulture("fr-FR")

        ' The following line provides localization for the application's user interface.
        Thread.CurrentThread.CurrentUICulture = Culture

        ' The following line provides localization for data formats.
        Thread.CurrentThread.CurrentCulture = Culture

        ' Set this culture as the default culture for all threads in this application.  
        ' Note: The following properties are supported in the .NET Framework 4.5+
        CultureInfo.DefaultThreadCurrentCulture = Culture
        CultureInfo.DefaultThreadCurrentUICulture = Culture

        With oTmr
            .Interval = 100
            AddHandler .Tick, Sub()
                                  Dim tps = DateDiff(DateInterval.Second, startTime, Now)
                                  Dim h As Integer = Math.Floor(tps / 3600)
                                  Dim m As Integer = Math.Floor((tps - (h * 3600)) / 60)
                                  Dim s As Integer = tps - h * 3600 - m * 60
                                  Result_txt.Text = "Début traitement : " & startTime & ", Temps écoulé : " & Droite("00" & h, 2) & ":" & Droite("00" & m, 2) & ":" & Droite("00" & s, 2) & vbCrLf & strMsg.ToString
                                  Result_txt.Refresh()
                              End Sub
        End With
    End Sub
    Sub gridView1_CustomDrawRowIndicator(sender As Object, e As DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs)
        e.Info.DisplayText = e.RowHandle.ToString()
    End Sub

    Sub Python_Generator(ByVal PythonName As String, ByVal PythonText As String)
        Cod_Python_txt.Text = PythonName
        Nom_Python_txt.Text = PythonText
        withConn = FindLibelle("withConn", "Cod_Python", PythonName, "Param_Python")
        With imgList
            .Images.Clear()
            .Images.Add(My.Resources.calendrier)
            .Images.Add(My.Resources.MenuLocal)
            .ImageSize = New Size(10, 10)
        End With


        Dim Cod_Sql As String = "Select * from Param_Python_Arguments where Cod_Python='" & PythonName & "' order by rang"
        Tbl = DATA_READER_GRD(Cod_Sql)
        Dim C1, C2, C3, C4, C5 As Object
        With Tbl
            For i = 0 To .Rows.Count - 1
                C1 = IsNull(Tbl.Rows(i).Item("Argument"), "")
                C2 = IsNull(Tbl.Rows(i).Item("Lib_Argument"), "")
                C3 = GetDefaultValue(IsNull(.Rows(i).Item("Default_Value"), ""))
                C4 = IsNull(Tbl.Rows(i).Item("Fonction_Critere"), "")
                C5 = IsNull(Tbl.Rows(i).Item("Typ_Critere"), "")
                Arguments_Grd.Rows.Add(C1, C2, C3, C4, C5)
                If C1.trim.ToString.ToUpper = "IDSOC" Then Arguments_Grd.Rows(i).Visible = False
            Next
        End With
    End Sub
    Private Sub Arguments_Grd_CellPainting(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellPaintingEventArgs) Handles Arguments_Grd.CellPainting
        If e.ColumnIndex <> Valeur.Index Or e.RowIndex < 0 Then Exit Sub
        Dim oX, oY As Integer
        oX = e.CellBounds.Location.X + e.CellBounds.Width - 16
        oY = (e.RowIndex + 1) * e.CellBounds.Height
        With Tbl.Rows(e.RowIndex)
            If IsNull(.Item("Fonction_Critere"), "") = "Calender" Then
                e.Graphics.DrawImage(My.Resources.calendrier, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            ElseIf IsNull(.Item("Fonction_Critere"), "") = "Appel_Zoom" Then
                e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            ElseIf IsNull(.Item("Fonction_Critere"), "") = "Combo" Then
                e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            ElseIf IsNull(.Item("Fonction_Critere"), "") = "Boolean" Then
                e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            ElseIf IsNull(.Item("Fonction_Critere"), "") = "File" Then
                e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            ElseIf IsNull(.Item("Fonction_Critere"), "") = "Path" Then
                e.Graphics.DrawImage(My.Resources.MenuLocal, oX, oY)
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = True
            Else
                Arguments_Grd.Item(Valeur.Index, e.RowIndex).ReadOnly = False
            End If
        End With
    End Sub
    Private Sub Arguments_Grd_DoubleClick(ByVal sender As Object, ByVal e As System.EventArgs) Handles Arguments_Grd.DoubleClick
        Dim r, c As Integer
        r = Arguments_Grd.CurrentRow.Index
        c = Arguments_Grd.CurrentCell.ColumnIndex
        If c <> Valeur.Index Or r < 0 Then Exit Sub
        Dim FonctionCritere As String = Arguments_Grd.Item(Fonction_Critere.Index, r).Value
        Dim oCell As DataGridViewTextBoxCell = TryCast(Arguments_Grd.Item(Valeur.Index, r), DataGridViewTextBoxCell)
        Select Case FonctionCritere
            Case "Calender"
                Appel_Calender(oCell, Me)
            Case "Boolean"
                Appel_Zoom_Boolean(oCell, Me)
            Case "Appel_Zoom"
                Dim Cod_Sql As String = "Select * from Param_Python_Arguments where Argument='" & Arguments_Grd.Item(Argument.Index, r).Value & "' and Cod_Python = '" & Cod_Python_txt.Text & "' order by rang"
                Dim Condition As String = "1=1"
                Dim Tbl As New DataTable
                Tbl = DATA_READER_GRD(Cod_Sql)
                With Tbl
                    If Tbl.Rows.Count > 0 Then
                        If RTrim(LTrim(IsNull(.Rows(0).Item("Condition"), ""))) <> "" Then
                            Condition = IsNull(.Rows(0).Item("Condition"), "")
                            Dim Condition1 As String()
                            Condition1 = Split(Condition, "&")
                            Dim Longeur As Integer = UBound(Condition1)
                            Condition = ""

                            For i As Integer = 0 To Longeur
                                If Condition1(i).Trim.ToUpper = "IDSOC" Then
                                    Condition1(i) = Societe.id_Societe
                                Else
                                    For k = 0 To Arguments_Grd.RowCount - 1
                                        If UCase(Arguments_Grd.Item(Argument.Index, k).Value) = UCase(LTrim(RTrim(Condition1(i)))) Then
                                            Condition1(i) = Arguments_Grd.Item(Valeur.Index, k).Value
                                        End If
                                    Next
                                End If
                                Condition = RTrim(Condition.Trim("""")) & RTrim(LTrim(Condition1(i)).Trim(""""))
                            Next
                        End If
                        Appel_Zoom(.Rows(0).Item("Champs_01"), .Rows(0).Item("Champs_02"), .Rows(0).Item("Table_Argument"), Condition, oCell, Me)
                    End If
                End With
            Case "Combo"
                Dim Cod_Sql As String = "Select * from Param_Python_Arguments where Argument='" & Arguments_Grd.Item(Argument.Index, r).Value & "' and Cod_Python = '" & Cod_Python_txt.Text & "' order by rang"
                Dim Condition As String = "1=1"
                Dim Tbl As New DataTable
                Tbl = DATA_READER_GRD(Cod_Sql)
                With Tbl
                    If Tbl.Rows.Count > 0 Then
                        Appel_Zoom_Boolean(oCell, Me, IsNull(.Rows(0).Item("Table_Critere"), ""))
                    End If
                End With
            Case "File"
                Dim OpenFileDialog As New OpenFileDialog
                OpenFileDialog.InitialDirectory = importPath
                OpenFileDialog.AutoUpgradeEnabled = False
                OpenFileDialog.Filter = "Tous les fichiers (*.*)|*.*"
                If (OpenFileDialog.ShowDialog(Me) = System.Windows.Forms.DialogResult.OK) Then
                    importPath = System.IO.Path.GetFullPath(OpenFileDialog.FileName)
                    Dim FileName As String = OpenFileDialog.FileName
                    oCell.Value = FileName
                End If
            Case "Path"
                Dim oFolderBrowserDialog As New FolderBrowserDialog
                oFolderBrowserDialog.SelectedPath = My.Computer.FileSystem.SpecialDirectories.MyDocuments
                If (oFolderBrowserDialog.ShowDialog(Me) = System.Windows.Forms.DialogResult.OK) Then
                    Dim Path As String = oFolderBrowserDialog.SelectedPath
                    oCell.Value = Path
                End If
        End Select
    End Sub
    Private Sub Visualiser_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Run_pb.Click
        Request()
    End Sub
    Dim strMsg As New System.Text.StringBuilder
    Sub Request()
        startTime = Now
        pBar.Visible = True
        Me.Cursor = Cursors.WaitCursor
        strMsg.Clear()
        Result_txt.ResetText()

        Try

            codeText = FindLibelle("Text_Code", "Cod_Python", Cod_Python_txt.Text, "Param_Python")
            Dim shouldImportDate As Boolean = False
            With Arguments_Grd
                For i = 0 To .RowCount - 1
                    Dim val = .Item(Valeur.Index, i).Value
                    Select Case .Item(Typ_Critere.Index, i).Value
                        Case "int"
                            If Not IsNumeric(val) Then val = 0
                            codeText = .Item(Argument.Index, i).Value & " = " & CInt(val) & vbCrLf & codeText
                        Case "float"
                            If Not IsNumeric(val) Then val = 0
                            codeText = .Item(Argument.Index, i).Value & " = " & CDbl(val) & vbCrLf & codeText
                        Case "smalldatetime"
                            If Not EstDate(val) Then val = Now
                            shouldImportDate = True
                            codeText = .Item(Argument.Index, i).Value & " = datetime.date(" & CDate(val).Year & ", " & CDate(val).Month & ", " & CDate(val).Day & ")" & vbCrLf & codeText
                        Case Else
                            val = val.Replace("\\", "\")
                            val = val.Replace("\", "\\")
                            codeText = CStr(.Item(Argument.Index, i).Value).ToUpper & " = """ & val & """" & vbCrLf & codeText
                    End Select
                Next
                If shouldImportDate Then
                    codeText = "import datetime" & vbCrLf & codeText
                End If

                oTmr.Start()
                BackgroundWorker1.RunWorkerAsync()
            End With
        Catch ex As Exception
            BackgroundWorker1.CancelAsync()
            strMsg.AppendLine(ex.Message)
            oTmr.Stop()
        End Try
    End Sub
    Function setFormatExport(Str As Object, NbChar As Integer, Optional EstNumeric As Boolean = False) As String
        If Not EstNumeric Then
            Return Gauche(IsNull(Str, "").Replace(Chr(13), Chr(32)) & StrDup(NbChar, Chr(32)), NbChar)
        Else
            Return Droite(StrDup(NbChar, "0") & IsNull(Str, 0), NbChar)
        End If

    End Function
    Private Sub Close_D_Click(sender As Object, e As EventArgs) Handles Close_pb.Click
        Me.Close()
    End Sub
    Private Sub SourceCode_D_Click(sender As Object, e As EventArgs) Handles python_pb.Click
        Dim f As New Zoom_SqlText
        With f
            .Sql_Text.Text = If(withConn, setPythonConn(codeText, False), codeText)
            .ShowDialog()
        End With
    End Sub
    Function GetDefaultValue(ByVal Relation) As String
        Dim Variable As New ArrayList
        Dim ValeurVariable As New ArrayList
        Try
            ' Chargement des variables de critères et leurs valeurs
            If Microsoft.VisualBasic.Left(Relation, 1) = Chr(34) Then
                Relation = Relation.Replace(Chr(34), "")
            End If
            If Microsoft.VisualBasic.Left(Relation, 1) = "{" Then
                Relation = Relation.Replace("{", "").Replace("}", "")
                For j = 0 To Arguments_Grd.RowCount - 1
                    If Not Arguments_Grd.Item(Argument.Index, j).Value Is Nothing Then
                        If Relation.ToUpper.Contains(Arguments_Grd.Item(Argument.Index, j).Value.ToUpper) Then
                            Variable.Add(Arguments_Grd.Item(Argument.Index, j).Value)
                            ValeurVariable.Add(Arguments_Grd.Item(Valeur.Index, j).Value)
                        End If
                    End If
                Next
                For j = 0 To Variable.Count - 1
                    If Relation.toupper.contains(Variable(j).toupper) Then
                        Relation = Relation.Replace(Variable(j), "'" & ValeurVariable(j) & "'")
                    End If
                Next
                Relation = IsNull(CnExecuting(Relation).Fields(0).Value, "")
                'Cas des Variables Globales
            ElseIf Relation.ToString.Trim.ToUpper.Contains("GV_") Then
                Relation = GlobalVar(Relation.trim.ToString)
            End If
        Catch ex As Exception
            ErrorMsg(ex)
        End Try
        Return Relation
    End Function

    Private Sub Arguments_Grd_EditingControlShowing(sender As Object, e As DataGridViewEditingControlShowingEventArgs) Handles Arguments_Grd.EditingControlShowing
        RemoveHandler e.Control.KeyPress, AddressOf CheckCell
        RemoveHandler e.Control.KeyPress, AddressOf CheckCell
        If Arguments_Grd.CurrentCell.ColumnIndex = Valeur.Index Then
            AddHandler e.Control.KeyPress, AddressOf CheckCell
        End If
    End Sub
    Private Sub CheckCell(ByVal sender As System.Object, ByVal e As System.Windows.Forms.KeyPressEventArgs)
        With Arguments_Grd
            If .CurrentRow Is Nothing Then Exit Sub
            Dim c As Integer = .CurrentCell.ColumnIndex
            Dim r As Integer = .CurrentRow.Index
            Select Case IsNull(.Item(Typ_Critere.Index, r).Value, "")
                Case "int", "bigint"
                    ControleSaisie(sender, e, True, True, False, False, False)
                Case "float"
                    ControleSaisie(sender, e, True, False, False, False, False)
            End Select
        End With


    End Sub
    Sub bg_run(sender As Object, e As Object) Handles BackgroundWorker1.DoWork
        executerCodePython(codeText, strMsg, withConn)
    End Sub

    Private Sub BackgroundWorker1_RunWorkerCompleted(sender As Object, e As RunWorkerCompletedEventArgs) Handles BackgroundWorker1.RunWorkerCompleted
        Try
            ' Arrêter le timer
            oTmr.Stop()

            ' Mise à jour finale pour garantir l'affichage du résultat complet
            Dim tps = DateDiff(DateInterval.Second, startTime, Now)
            Dim h As Integer = Math.Floor(tps / 3600)
            Dim m As Integer = Math.Floor((tps - (h * 3600)) / 60)
            Dim s As Integer = tps - h * 3600 - m * 60

            Result_txt.Text = "Début traitement : " & startTime &
                         ", Temps écoulé : " & Droite("00" & h, 2) & ":" &
                         Droite("00" & m, 2) & ":" & Droite("00" & s, 2) &
                         vbCrLf & strMsg.ToString
            Result_txt.Refresh()

            ' Masquer la barre de progression et restaurer le curseur
            pBar.Visible = False
            Me.Cursor = Cursors.Default

            ' Afficher un message en cas d'erreur
            If e.Error IsNot Nothing Then
                strMsg.AppendLine(vbCrLf & "ERREUR: " & e.Error.Message)
                Result_txt.Text &= vbCrLf & "ERREUR: " & e.Error.Message
                MessageBox.Show("Une erreur s'est produite lors de l'exécution." & vbCrLf & e.Error.Message,
                          "Erreur", MessageBoxButtons.OK, MessageBoxIcon.Error)
            ElseIf e.Cancelled Then
                Result_txt.Text &= vbCrLf & "Traitement annulé."
            Else
                ' Afficher un message de succès
                Result_txt.Text &= vbCrLf & "Traitement terminé avec succès."
            End If

        Catch ex As Exception
            ErrorMsg(ex)
            pBar.Visible = False
            Me.Cursor = Cursors.Default
        End Try
    End Sub
End Class